
# You can name this whatever you want
name: update

# You will get an error on the automatic updates committing
# if you do not have this line
# You didn't need it before, which is why a lot of yml job files
# you see will not have it (but you need it now!!!)
permissions:
  contents: write
  
# The 'on' section is about when this is run
# workflow_dispatch makes there be a button on GitHub to let you run it manually
# schedule and cron make it run at certain frequencies
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Installed package list
      run: apt list --installed
    - name: Remove Chrome
      run: sudo apt purge google-chrome-stable
    - name: Remove default Chromium
      run: sudo apt purge chromium-browser
    - name: Install a new Chromium
      run: sudo apt install -y chromium-browser 
    - name: Install all necessary packages
      run: pip install pandas requests beautifulsoup4 html5lib sendgrid dotenv base64  webdriver-manager selenium
    - name: Scraping today's data
      run: python scraper.py
    - name: Commit and push any changes
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
